import express from "express";
import { isAuthor } from "../middleware/auth.middleware.js";
import { createBlog } from "../services/blog.service.js";
const router = express.Router();
router.post("/blog/create", isAuthor,createBlog);
router.post("/blog/details", (req, res) => {});
router.post("/blogs", (req, res) => {});
router.post("/blog/update/:id", (req, res) => {});
router.post("/blog/delete/:id", (req, res) => {});
export { router };
